export const GET_SLIDER_IMAGES_START = "GET_SLIDER_IMAGES_START";
export const GET_SLIDER_IMAGES_SUCCESS = "GET_SLIDER_IMAGES_SUCCESS";
export const GET_SLIDER_IMAGES_FAILED = "GET_SLIDER_IMAGES_FAILED";

export const GET_FEATURED_PRODUCTS_START = "GET_FEATURED_PRODUCTS_START";
export const GET_FEATURED_PRODUCTS_SUCCESS = "GET_FEATURED_PRODUCTS_SUCCESS";
export const GET_FEATURED_PRODUCTS_FAILED = "GET_FEATURED_PRODUCTS_FAILED";

export const GET_PRODUCT_START = "GET_PRODUCT_START";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

export const SEARCH_START = "SEARCH_START";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILED = "SEARCH_FAILED";


export const ADD_REVIEW_START = "ADD_REVIEW_START";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FIALD = "ADD_REVIEW_FIALD";
export const ADD_REVIEW_RESET = "ADD_REVIEW_RESET";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";

export const GET_CATEGORIES_START = "GET_CATEGORIES_START";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";
