export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";



export const LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const LOGIN_START = "USER_LOGIN_START";
export const LOGIN_FIALD = "USER_LOGIN_FIALD";

export const REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const REGISTER_START = "USER_REGISTER_START";
export const REGISTER_FIALD = "USER_REGISTER_FIALD";