export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";



export const LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const LOGIN_START = "USER_LOGIN_START";
export const LOGIN_FIALD = "USER_LOGIN_FIALD";

export const REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const REGISTER_START = "USER_REGISTER_START";
export const REGISTER_FIALD = "USER_REGISTER_FIALD";

export const GET_USER_START = "GET_USER_START";
export const GET_USER_FIALD = "GET_USER_FIALD";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const UPDATE_START = "UPDATE_START";
export const UPDATE_FIALD = "UPDATE_FIALD";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";


export const UPDATE_REVIEWS_SUCCESS = "UPDATE_REVIEWS_SUCCESS";
